#!/usr/bin/env python3
"""Apply decisions to an alignment and emit payload.json for build_transcript_docx.py.

  python3 build_payload.py alignment.json decisions.json --out payload.json
  python3 build_payload.py --schema        # print the decisions format

Everything the caller decided — how each disputed span reads, which filler comes
out, which recovered passages go in, how speakers are named — is applied here, in
one deterministic pass. Rerun it after each round of review; it is cheap, so
nothing has to be regenerated by hand.
"""

import argparse
import json
import os
import re
import sys

SCHEMA = r"""
decisions.json
--------------
Every key is optional. Anything you leave out keeps the aligner's result, so a
first pass can be short and later passes can add to it.

{
  "meta": {                       // merged into the document header table
    "Interview":   "Dana Whitfield, VP Operations, Acme Materials",
    "Project":     "Calyxo Growth Strategy (CLXO02)",
    "Date of call": "2026-07-21",
    "Interviewer(s)": "Andrew Gartley (Newry)"
  },
  "title": "Interview Transcript — Dana Whitfield, Acme Materials",
  "notes": ["Free-text caveats shown under the header."],

  "speakers": {                   // rename the source's labels to real people
    "Speaker 2": "Dana Whitfield (Acme Materials)",
    "Andrew Gartley": "Andrew Gartley (Newry)"
  },

  "glossary": {                   // applied everywhere, whole words, case-aware
    "naphion": "Nafion",
    "chemores": "Chemours"
  },

  // A resolution replaces EXACTLY the disputed span shown in that site's
  // "variants" — not the surrounding phrase. If the variants are "Veltrix" and
  // "Veltrex", the resolution is "Veltrix", not "Veltrix Polymers"; including the
  // next word duplicates it in the output.
  "sites": {                      // decisions on alignment.needs_judgment
    "7": {"resolution": "Veltrix"},
    "8": {"flag": true,           // leave open: inline marker + appendix row
          "issue": "Only two sources and no majority; nearly fourfold apart.",
          "best_guess": "60 kilotons",
          "confidence": "low"},
    "9": {"resolution": "[inaudible 14:02]"},
    "10": {"flag": true, "status": "reviewed-unresolved",
           "issue": "Andrew listened back; still not audible."}
  },

  // Filler is normally decided a group at a time — sixty "um"s are one decision.
  // Group keys come from review.json's filler_groups. Per-id entries win over
  // the group, so a group can be removed wholesale with a few instances spared.
  "filler": {
    "remove_groups": ["filler_word:um", "filler_word:uh", "filler_phrase:you know"],
    "keep_groups":   ["hedge:i think"],
    "remove": [412, 415],         // individual candidate ids
    "keep":   [88]                // spare these even if their group is removed
  },

  "coverage_gaps": {              // decisions on alignment.coverage_gaps
    "0": {"include": true, "speaker": "Dana Whitfield (Acme Materials)"},
    "1": {"include": false}       // judged a hallucination
  }
}

Sites with no entry are flagged, on the principle that an undecided disagreement
should surface rather than quietly take the anchor's reading.
"""

SITE_TOKEN = re.compile(r"\{\{SITE:(\d+)\}\}")


def die(msg):
    sys.exit(f"error: {msg}")


def require(module, package):
    """Fail with the install command rather than a bare ImportError."""
    try:
        __import__(module)
    except ImportError:
        die(f"this step needs the {package} package: pip install {package}")


def _cmp_tokens(text):
    """Tokens reduced to letters and digits, for support comparison.
    '$4,999' -> ['4999'];  "won't do" -> ['wont', 'do']."""
    return [t for t in (re.sub(r"[^a-z0-9]", "", w.lower())
                        for w in (text or "").split()) if t]


def unsupported_tokens(resolution, site, glossary):
    """Tokens in a resolution that no source said and the glossary doesn't supply.

    A resolution is meant to choose between what the sources offer, or to apply a
    known correct form. A token from neither is invented — the one failure the
    output cannot survive, because unflagged text is trusted completely. The
    Calyxo Joel transcript shipped '$4,995' where one source said '$4,999' and the
    other garbled it; this is the check that would have caught it.
    """
    if not resolution or resolution.lstrip().startswith("[inaudible"):
        return []
    supported = set()
    for variant in site.get("variants", []):
        supported.update(_cmp_tokens(variant.get("text")))
    for right in (glossary or {}).values():
        supported.update(_cmp_tokens(right))
    return [t for t in _cmp_tokens(resolution) if t not in supported]


def apply_glossary(text, glossary):
    """Whole-word substitution that respects the casing already in the text."""
    for wrong, right in glossary.items():
        if not wrong:
            continue

        def replace(match, right=right):
            found = match.group(0)
            if found.isupper() and len(found) > 1:
                return right.upper()
            if found[:1].isupper():
                return right[:1].upper() + right[1:]
            return right

        text = re.sub(r"\b%s\b" % re.escape(wrong), replace, text,
                      flags=re.IGNORECASE)
    return text


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("alignment", nargs="?", help="alignment.json from align_sources.py")
    ap.add_argument("decisions", nargs="?", help="decisions.json")
    ap.add_argument("--out", help="output payload.json")
    ap.add_argument("--schema", action="store_true")
    ap.add_argument("--full", action="store_true",
                    help="deeper pass: flag wording-only ties too, instead of "
                         "letting them take the timing anchor's reading. The "
                         "default is lean — figures, names and negations flag "
                         "either way")
    ap.add_argument("--flag-floor-sites", type=int, default=40,
                    help="judgment-site count above which zero flags is refused "
                         "(default 40)")
    ap.add_argument("--no-flags-ok", action="store_true",
                    help="acknowledge that a large run legitimately has no flags; "
                         "the acknowledgement is recorded in the document")
    ap.add_argument("--blob-share-warn", type=float, default=15.0,
                    help="%% of words in merged-speaker turns above which the "
                         "document must disclose unverified attribution")
    args = ap.parse_args()

    if args.schema:
        print(SCHEMA)
        return
    if not args.alignment or not args.out:
        die("alignment.json and --out are required (or pass --schema)")

    with open(args.alignment, "r", encoding="utf-8") as fh:
        alignment = json.load(fh)
    decisions = {}
    if args.decisions:
        with open(args.decisions, "r", encoding="utf-8") as fh:
            decisions = json.load(fh)

    site_decisions = {str(k): v for k, v in (decisions.get("sites") or {}).items()}
    speakers = decisions.get("speakers") or {}
    glossary = decisions.get("glossary") or {}
    filler = decisions.get("filler") or {}
    remove_groups = set(filler.get("remove_groups") or [])
    keep_ids = set(filler.get("keep") or [])
    filler_remove = set(filler.get("remove") or [])
    known_groups = {g["key"] for g in alignment.get("filler_groups", [])}
    unknown_groups = sorted(remove_groups - known_groups)
    if unknown_groups:
        die(f"decisions reference filler groups not in the alignment: "
            f"{unknown_groups}\n  available: {sorted(known_groups)}")
    for group in alignment.get("filler_groups", []):
        if group["key"] in remove_groups:
            filler_remove |= set(group["ids"])
    filler_remove -= keep_ids
    gap_decisions = {str(k): v for k, v in
                     (decisions.get("coverage_gaps") or {}).items()}

    sites_by_id = {str(s["id"]): s for s in alignment.get("needs_judgment", [])}
    unknown = sorted(set(site_decisions) - set(sites_by_id), key=str)
    if unknown:
        die(f"decisions reference sites not in the alignment: {unknown}")

    # ---- resolve each disputed span
    conflicts, conflict_no, demoted, lean_wording = [], 0, [], []
    lean_times = []
    replacement_for = {}
    for site_id, site in sites_by_id.items():
        decision = site_decisions.get(site_id, {})
        anchor_reading = next(
            (v["text"] for v in site["variants"]
             if v["source"] == alignment.get("anchor")), "")

        resolution = decision.get("resolution")
        if resolution is not None:
            longest_variant = max(
                (len(v["text"].split()) for v in site["variants"]), default=0)
            if len(resolution.split()) > longest_variant + 1:
                sys.stderr.write(
                    f"warning: site {site_id} resolution is {len(resolution.split())} "
                    f"words but the longest variant is {longest_variant}. A "
                    f"resolution replaces only the disputed span — check for "
                    f"duplicated words around it in the output.\n")
        # Lean pass: a wording-only tie changes no claim, and flagging forty of
        # them buries the ten that matter. Take the anchor's reading and say how
        # many were handled that way; the deeper pass can revisit them.
        if (not args.full and resolution is None and not decision.get("flag")
                and site.get("category") == "wording"):
            lean_wording.append(site_id)
            if site.get("time"):
                lean_times.append(site["time"])
            replacement_for[site_id] = anchor_reading
            continue

        invented = unsupported_tokens(resolution, site, glossary)
        if invented:
            demoted.append((site_id, resolution, invented))
            decision = dict(decision)
            decision["issue"] = (
                f"Resolution {resolution!r} was not supported by any source "
                f"(unmatched: {', '.join(invented)}), so it was demoted to a flag "
                f"rather than written into the transcript.")
            decision["confidence"] = "low"
            resolution = None

        flagged = decision.get("flag") or resolution is None
        if not flagged:
            replacement_for[site_id] = resolution
            continue

        conflict_no += 1
        text = resolution if resolution is not None else anchor_reading
        replacement_for[site_id] = f"{text} [CONFLICT {conflict_no}]".strip()
        conflicts.append({
            "id": conflict_no,
            "site_id": site_id,
            "time": site.get("time", ""),
            "context": decision.get("context") or _context_for(alignment, site),
            "variants": [v for v in site["variants"] if v["text"]],
            "issue": decision.get("issue") or _default_issue(site, alignment),
            "best_guess": decision.get("best_guess", text),
            "confidence": decision.get("confidence", "low"),
            "status": decision.get("status", "open"),
        })

    # ---- flagging floor
    # Flagging discipline is the thing that decayed across the Calyxo project:
    # the first interviews carried three flags each, the last four carried none,
    # while the scripts behaved identically throughout. Deciding hundreds of
    # judgment sites and flagging nothing is not a credible outcome, so refuse
    # rather than ship silent confidence.
    floor_note = None
    judgment_seen = len(sites_by_id) - len(lean_wording)
    if judgment_seen >= args.flag_floor_sites and not conflicts:
        if not args.no_flags_ok:
            die(f"{len(sites_by_id)} sites needed judgment and none were flagged.\n"
                f"  Re-read the number, negation and entity sites in "
                f"alignment.review.json and flag what you would not want quoted.\n"
                f"  If every one is genuinely settled, rerun with --no-flags-ok; "
                f"that acknowledgement is recorded in the document.")
        floor_note = (f"All {len(sites_by_id)} sites requiring judgment were "
                      f"resolved and none were flagged; the reviewer explicitly "
                      f"acknowledged this rather than it passing unnoticed.")

    # ---- filler removals, keyed by turn so offsets stay local
    removals_by_turn = {}
    for cand in alignment.get("filler_candidates", []):
        if cand["id"] in filler_remove:
            removals_by_turn.setdefault(cand["turn"], []).append(cand)

    # ---- build turns
    turns = []
    marked_sites = set()
    turn_of_site = {str(s["id"]): s.get("turn")
                    for s in alignment.get("needs_judgment", [])}
    for turn in alignment.get("turns", []):
        text = turn.get("text") or ""
        edited = False

        for cand in sorted(removals_by_turn.get(turn["turn"], []),
                           key=lambda c: -c["start"]):
            target = cand["text"]
            # Deleting a word must not delete the sentence boundary that happened
            # to be attached to it: "doing this well?" -> "doing this?" rather
            # than running two sentences together. Clause commas can go.
            terminal = ""
            match_end = re.search(r"[.?!]+$", target)
            if match_end:
                terminal = match_end.group(0)
            pattern = re.compile(r"\s*" + re.escape(target) + r"(?=\s|$)")
            new_text, count = pattern.subn(terminal, text, count=1)
            if count:
                text = new_text
                edited = True
            else:
                sys.stderr.write(
                    f"warning: filler candidate {cand['id']} ({target!r}) no "
                    f"longer present in turn {turn['turn']}; skipped\n")

        def swap(match):
            sid = match.group(1)
            marked_sites.add(sid)
            if sid not in replacement_for:
                sys.stderr.write(f"warning: no decision for site {sid}\n")
                return ""
            return replacement_for[sid]

        text = SITE_TOKEN.sub(swap, text)
        text = apply_glossary(text, glossary)
        text = re.sub(r"\s+", " ", text).strip()
        text = re.sub(r"\s+([,.;:?!])", r"\1", text)
        if edited:
            # Removing a leading "So," leaves a lowercase sentence start. That is
            # our own edit's damage, not the speaker's grammar, so repair it —
            # nothing else about the wording is touched.
            text = _recapitalize(text)
        if not text:
            continue

        speaker = turn.get("speaker") or "Unidentified speaker"
        turns.append({
            "time": turn.get("time", ""),
            "speaker": speakers.get(speaker, speaker),
            "text": text,
        })

    # A site spanning a turn boundary has no placeholder in the text, so its
    # [CONFLICT n] marker never landed and the appendix row pointed at nothing.
    # The 4-turn fixture never hit this; a real interview hit it 24 times out of
    # 79 flags. Append the marker to the site's own turn so every row is findable.
    orphans = []
    anchor_turns = alignment.get("turns", [])
    for conflict in conflicts:
        sid = str(conflict.get("site_id"))
        if sid in marked_sites:
            continue
        t_idx = turn_of_site.get(sid)
        time_key = (anchor_turns[t_idx].get("time")
                    if t_idx is not None and 0 <= t_idx < len(anchor_turns) else None)
        placed = False
        if time_key:
            for turn in turns:
                if turn.get("time") == time_key:
                    turn["text"] = f"{turn['text']} [CONFLICT {conflict['id']}]"
                    placed = True
                    break
        if not placed:
            orphans.append(conflict["id"])

    # ---- recovered passages the anchor missed
    inserted = 0
    for idx, gap in enumerate(alignment.get("coverage_gaps", [])):
        decision = gap_decisions.get(str(idx), {})
        if not decision.get("include"):
            continue
        speaker = decision.get("speaker") or gap.get("speaker_in_source") \
            or "Unidentified speaker"
        text = apply_glossary(decision.get("text") or gap["text"], glossary)
        position = min(gap["after_turn"] + 1 + inserted, len(turns))
        turns.insert(position, {
            "time": gap.get("time", ""),
            "speaker": speakers.get(speaker, speaker),
            "text": text,
        })
        inserted += 1

    # ---- header
    meta = {}
    source_summary = "; ".join(
        f"{s['name']} ({s['turns']} turns, {s['words']} words)"
        for s in alignment.get("sources", []))
    n_ind = alignment.get("independent_sources")
    meta["Sources reconciled"] = (
        f"{source_summary}. {n_ind} independent transcription"
        f"{'s' if n_ind != 1 else ''}."
        + ("" if alignment.get("majority_possible")
           else " Fewer than three, so no disagreement could be settled by majority."))
    meta["Timing anchor"] = alignment.get("anchor", "")
    meta["Verbatim standard"] = "Clean verbatim (filler and false starts removed)"
    meta.update(decisions.get("meta") or {})
    ordered = {}
    for key in ("Interview", "Project", "Date of call", "Interviewer(s)",
                "Participants"):
        if key in meta:
            ordered[key] = meta.pop(key)
    ordered.update(meta)

    notes = list(decisions.get("notes") or [])
    if floor_note:
        notes.append(floor_note)
    if lean_wording:
        notes.append(
            f"{len(lean_wording)} disagreement(s) about wording alone — where no "
            f"figure, name or negation was in question — took the timing anchor's "
            f"reading rather than being flagged, at "
            f"{', '.join(lean_times) if lean_times else 'times not recorded'}"
            f". A deeper pass can revisit them.")
    if demoted:
        notes.append(
            f"{len(demoted)} resolution(s) proposed a reading no source supported "
            f"and were flagged instead of written into the transcript.")

    # Attribution that was never repaired reads identically to attribution that
    # was verified, so say which it is. Ryan and Gill shipped at 61% and 69%
    # merged-speaker words with no disclosure.
    turn_words = [len((t.get("text") or "").split()) for t in turns]
    total_words = sum(turn_words) or 1
    blob_words = sum(w for w in turn_words if w > 250)
    blob_share = 100.0 * blob_words / total_words
    disclose_blob = blob_words > 0 and blob_share >= args.blob_share_warn
    if disclose_blob:
        already = any(re.search(r"attribut|merged|collapsed|speaker", n, re.I)
                      for n in notes)
        if not already:
            notes.append(
                f"{blob_share:.0f}% of words remain in turns that merge speakers, "
                f"so attribution in those passages is the source's and was not "
                f"verified by this pipeline.")

    votes = alignment.get("resolved_by_vote", [])
    if votes:
        consequential = [v for v in votes
                         if v["category"] in ("number", "negation", "entity")]
        notes.append(
            f"{len(votes)} disagreement{'s' if len(votes) != 1 else ''} between "
            f"sources were settled by majority across independent sources rather "
            f"than flagged"
            + (f", including {len(consequential)} involving a number, a negation, "
               f"or a named entity" if consequential else "") + ".")
    gaps_kept = alignment.get("kept_despite_gaps", [])
    if gaps_kept:
        n = len(gaps_kept)
        notes.append(
            f"{n} {_plural(n, 'passage')} present in some sources but absent from "
            f"others {_plural(n, 'was', 'were')} kept, since a source that drops "
            f"content is not evidence the content is absent.")
    if inserted:
        notes.append(f"{inserted} passage(s) missing from the timing anchor were "
                     f"recovered from another source.")

    # Majority-settled figures, negations and names never reach a human. That is
    # the intended rule, but it left nobody able to see which decisions were made
    # on their behalf — the Calyxo Joel header said 44 of them and listed none.
    # These are recorded so a consultant can spot-check them against audio.
    settled_consequential = [
        {
            "time": v.get("time", ""),
            "category": v.get("category", ""),
            "resolution": v.get("resolution", ""),
            "margin": v.get("margin", ""),
            "variants": [x for x in (v.get("variants") or []) if x.get("text")],
        }
        for v in alignment.get("resolved_by_vote", [])
        if v.get("category") in ("number", "negation", "entity")
    ]

    payload = {
        "title": decisions.get("title") or "Reconciled Interview Transcript",
        "meta": ordered,
        "notes": notes,
        "turns": turns,
        "conflicts": conflicts,
        "settled_by_vote": settled_consequential,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)

    words = sum(len(t["text"].split()) for t in turns)
    anchor_words = next((s["words"] for s in alignment.get("sources", [])
                         if s["name"] == alignment.get("anchor")), 0)
    longest = max((s["words"] for s in alignment.get("sources", [])), default=0)
    print(f"wrote {args.out}")
    print(f"  turns:            {len(turns)}")
    print(f"  words:            {words}  (anchor had {anchor_words}, "
          f"longest source {longest})")
    print(f"  open conflicts:   {len(conflicts)}")
    if orphans:
        print(f"  WARNING: {len(orphans)} flag(s) could not be placed: {orphans}")
    if lean_wording:
        print(f"  lean pass:        {len(lean_wording)} wording-only "
              f"tie(s) took the anchor reading")
    for site_id, resolution, invented in demoted:
        print(f"  DEMOTED site {site_id}: resolution {resolution!r} unsupported by "
              f"any source ({', '.join(invented)}) — flagged instead")
    if disclose_blob:
        print(f"  NOTE: {blob_share:.0f}% of words are in merged-speaker turns; "
              f"the document now discloses that attribution is unverified there")
    print(f"  filler removed:   {len(filler_remove)} of "
          f"{len(alignment.get('filler_candidates', []))} candidates")
    undecided = [s for s in sites_by_id if s not in site_decisions]
    if undecided:
        print(f"  NOTE: {len(undecided)} site(s) had no decision and were flagged: "
              f"{sorted(undecided, key=int)}")
    # Coverage check: the whole point of merging is not to lose speech.
    if longest and words < longest * 0.9:
        print(f"  WARNING: output is {100 - words * 100.0 / longest:.0f}% shorter "
              f"than the longest source. Check for dropped passages before "
              f"sending this to anyone.")


def _recapitalize(text):
    """Capitalize the opening word and any word that now starts a sentence."""
    if text and text[0].islower():
        text = text[0].upper() + text[1:]
    return re.sub(r"([.?!]\s+)([a-z])",
                  lambda m: m.group(1) + m.group(2).upper(), text)


def _plural(count, singular, plural=None):
    return singular if count == 1 else (plural or singular + "s")


def _context_for(alignment, site):
    turn = next((t for t in alignment.get("turns", [])
                 if t["turn"] == site.get("turn")), None)
    if not turn:
        return ""
    text = SITE_TOKEN.sub("…", turn.get("text") or "")
    return (text[:160] + "…") if len(text) > 160 else text


def _default_issue(site, alignment):
    absent = site.get("no_coverage") or []
    n = alignment.get("independent_sources", 0)
    reasons = []
    if absent:
        reasons.append(f"{', '.join(absent)} lack{'s' if len(absent) == 1 else ''} "
                       f"coverage here, so no majority is available")
    elif n < 3:
        reasons.append("only two independent sources, so a split cannot be voted on")
    else:
        reasons.append("sources split with no majority")
    if site.get("category") == "number":
        reasons.append("numeric difference, which phonetic similarity cannot settle")
    elif site.get("category") == "negation":
        reasons.append("the difference inverts the meaning")
    elif site.get("category") == "entity":
        reasons.append("a named entity not confirmed by the glossary")
    return "; ".join(reasons).capitalize() + "."


if __name__ == "__main__":
    main()
